/*
 * block-bench: filesystem-bypassing raw block-device microbenchmark.
 *
 * Opens a block device NODE directly (default /dev/vblk1, arg-overridable) with
 * open(dev, O_RDWR) and issues pread/pwrite at aligned offsets -- no filesystem,
 * no file, no mkfs, no io_uring. This is the control experiment that isolates
 * the OSv block layer (device_read/device_write -> bdev_read/bdev_write ->
 * strategy -> virtio-blk make_request) from any filesystem code above it.
 *
 * Queue depth is generated by N worker pthreads, each issuing SYNCHRONOUS
 * pread/pwrite in a loop. Effective queue depth == thread count: at any instant
 * up to N requests are outstanding in the block layer. If the block path
 * serializes (one synchronous bio at a time under a global lock), throughput
 * will NOT scale with N; if it is genuinely async, throughput scales until the
 * backing device saturates.
 *
 * Modes: seqread, randread, seqwrite, randwrite. All offsets and lengths are
 * 512-aligned so the run exercises the aligned fast path. A separate unaligned
 * smoke (a single 100-byte read at offset 0) verifies sub-block correctness of
 * the slow-path fallback.
 *
 * Emits one JSON line per run: {"block_bench":{...}} with the same field names
 * as apps/io-uring-bench so existing matrix tooling parses both identically.
 *
 * WARNING: seqwrite/randwrite DESTROY the contents of the target device. Only
 * point this at a scratch device.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdint.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <pthread.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <linux/fs.h>

/* ---- growable string buffer for JSON assembly (io-uring-bench style) ----- */

struct buf {
	char *p;
	size_t len;
	size_t cap;
};

static void buf_reserve(struct buf *b, size_t extra)
{
	if (b->len + extra + 1 <= b->cap)
		return;
	size_t ncap = b->cap ? b->cap * 2 : 4096;
	while (ncap < b->len + extra + 1)
		ncap *= 2;
	char *np = realloc(b->p, ncap);
	if (!np) {
		perror("realloc");
		exit(1);
	}
	b->p = np;
	b->cap = ncap;
}

static void buf_add(struct buf *b, const char *s, size_t n)
{
	buf_reserve(b, n);
	memcpy(b->p + b->len, s, n);
	b->len += n;
	b->p[b->len] = '\0';
}

#define buf_lit(b, s) buf_add((b), (s), sizeof(s) - 1)

static void buf_printf(struct buf *b, const char *fmt, ...)
{
	char tmp[512];
	va_list ap;
	va_start(ap, fmt);
	int n = vsnprintf(tmp, sizeof(tmp), fmt, ap);
	va_end(ap);
	if (n < 0)
		return;
	if ((size_t)n < sizeof(tmp)) {
		buf_add(b, tmp, (size_t)n);
		return;
	}
	buf_reserve(b, (size_t)n);
	va_start(ap, fmt);
	vsnprintf(b->p + b->len, (size_t)n + 1, fmt, ap);
	va_end(ap);
	b->len += (size_t)n;
}

static void buf_json_str(struct buf *b, const char *s)
{
	buf_lit(b, "\"");
	for (const unsigned char *c = (const unsigned char *)s; *c; c++) {
		switch (*c) {
		case '"':  buf_lit(b, "\\\""); break;
		case '\\': buf_lit(b, "\\\\"); break;
		case '\n': buf_lit(b, "\\n"); break;
		case '\r': buf_lit(b, "\\r"); break;
		case '\t': buf_lit(b, "\\t"); break;
		default:
			if (*c < 0x20)
				buf_printf(b, "\\u%04x", *c);
			else
				buf_add(b, (const char *)c, 1);
		}
	}
	buf_lit(b, "\"");
}

/* ---- latency histogram: fixed microsecond buckets (io-uring-bench style) - */

#define HIST_BUCKETS 4096

static unsigned lat_bucket(uint64_t us)
{
	if (us < 1024)
		return (unsigned)us;
	if (us < 65536)
		return 1024 + (unsigned)((us - 1024) >> 6);
	if (us < 1048576)
		return 2048 + (unsigned)((us - 65536) >> 10);
	unsigned b = 3072 + (unsigned)((us - 1048576) >> 14);
	return b < HIST_BUCKETS ? b : HIST_BUCKETS - 1;
}

static uint64_t bucket_us(unsigned b)
{
	if (b < 1024)
		return b;
	if (b < 2048)
		return 1024 + ((uint64_t)(b - 1024) << 6);
	if (b < 3072)
		return 65536 + ((uint64_t)(b - 2048) << 10);
	return 1048576 + ((uint64_t)(b - 3072) << 14);
}

static uint64_t percentile(const uint64_t *hist, uint64_t total, double pct)
{
	uint64_t target = (uint64_t)(total * pct);
	uint64_t acc = 0;
	for (unsigned i = 0; i < HIST_BUCKETS; i++) {
		acc += hist[i];
		if (acc >= target)
			return bucket_us(i);
	}
	return bucket_us(HIST_BUCKETS - 1);
}

/* ---- time + rng helpers ------------------------------------------------- */

static uint64_t now_ns(void)
{
	struct timespec ts;
	clock_gettime(CLOCK_MONOTONIC, &ts);
	return (uint64_t)ts.tv_sec * 1000000000ULL + (uint64_t)ts.tv_nsec;
}

/* SplitMix64: tiny, fast, dependency-free PRNG for random offsets. */
static uint64_t rng_mix(uint64_t *state)
{
	uint64_t z = (*state += 0x9e3779b97f4a7c15ULL);
	z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
	z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
	return z ^ (z >> 31);
}

/* ---- workload config ---------------------------------------------------- */

enum rw_mode { RW_SEQREAD, RW_RANDREAD, RW_SEQWRITE, RW_RANDWRITE };

static int is_write(enum rw_mode m)
{
	return m == RW_SEQWRITE || m == RW_RANDWRITE;
}

static int is_random(enum rw_mode m)
{
	return m == RW_RANDREAD || m == RW_RANDWRITE;
}

static const char *mode_name(enum rw_mode m)
{
	switch (m) {
	case RW_SEQREAD:   return "seqread";
	case RW_RANDREAD:  return "randread";
	case RW_SEQWRITE:  return "seqwrite";
	case RW_RANDWRITE: return "randwrite";
	}
	return "?";
}

struct cfg {
	const char *path;
	enum rw_mode mode;
	unsigned threads; /* == effective queue depth */
	unsigned bs;
	uint64_t span;    /* device byte range to operate over */
	unsigned runtime; /* seconds */
};

/* ---- per-thread worker -------------------------------------------------- */

struct worker {
	pthread_t tid;
	int fd;
	const struct cfg *c;
	uint64_t nblocks;
	uint64_t seq_start;    /* starting block for this thread's seq stream */
	uint64_t rng_state;
	volatile int *stop;

	/* results */
	uint64_t ios;
	uint64_t bytes;
	uint64_t errors;
	uint64_t hist[HIST_BUCKETS];
	void *bufmem;
};

static void *worker_run(void *arg)
{
	struct worker *w = (struct worker *)arg;
	const struct cfg *c = w->c;
	uint64_t seq = w->seq_start;

	while (!*w->stop) {
		uint64_t blk;
		if (is_random(c->mode))
			blk = rng_mix(&w->rng_state) % w->nblocks;
		else
			blk = seq++ % w->nblocks;

		off_t off = (off_t)(blk * c->bs);
		uint64_t t0 = now_ns();
		ssize_t r;
		if (is_write(c->mode))
			r = pwrite(w->fd, w->bufmem, c->bs, off);
		else
			r = pread(w->fd, w->bufmem, c->bs, off);
		uint64_t t1 = now_ns();

		if (r < 0) {
			w->errors++;
			continue;
		}
		w->bytes += (uint64_t)r;
		w->ios++;
		w->hist[lat_bucket((t1 - t0) / 1000)]++;
	}
	return NULL;
}

/* ---- unaligned slow-path correctness smoke ------------------------------ */

static int unaligned_smoke(const char *path)
{
	int fd = open(path, O_RDONLY);
	if (fd < 0)
		return -1;
	unsigned char small[100];
	ssize_t r = pread(fd, small, sizeof(small), 0);
	close(fd);
	return (r == (ssize_t)sizeof(small)) ? 0 : -1;
}

/* ---- one workload run: N threads against an already-open fd ------------- */

/*
 * Runs one (mode, threads, bs) config against fd for c->runtime seconds and
 * prints a single {"block_bench":{...}} JSON line. dev_bytes is the device
 * size (0 if unknown) used to clamp the span. Returns 0 on success, 1 if the
 * run produced errors or completed zero IOs.
 */
static int run_workload(int fd, const struct cfg *c, uint64_t dev_bytes)
{
	uint64_t span = c->span;
	if (dev_bytes > 0 && dev_bytes < span)
		span = dev_bytes;
	if (span < c->bs) {
		fprintf(stderr, "target too small: span=%llu bs=%u\n",
			(unsigned long long)span, c->bs);
		return 1;
	}
	uint64_t nblocks = span / c->bs;

	struct worker *ws = calloc(c->threads, sizeof(*ws));
	if (!ws) { perror("calloc"); return 1; }

	volatile int stop = 0;
	uint64_t seed = now_ns() ^ 0xdeadbeefcafef00dULL;

	for (unsigned i = 0; i < c->threads; i++) {
		ws[i].fd = fd;
		ws[i].c = c;
		ws[i].nblocks = nblocks;
		ws[i].seq_start = (nblocks / c->threads) * i;
		ws[i].rng_state = seed + 0x100000001b3ULL * (i + 1);
		ws[i].stop = &stop;
		if (posix_memalign(&ws[i].bufmem, 4096, c->bs) != 0) {
			fprintf(stderr, "posix_memalign\n");
			for (unsigned j = 0; j < i; j++)
				free(ws[j].bufmem);
			free(ws);
			return 1;
		}
		if (is_write(c->mode))
			memset(ws[i].bufmem, 0xa5, c->bs);
	}

	uint64_t start_ns = now_ns();
	unsigned started = 0;
	for (unsigned i = 0; i < c->threads; i++) {
		if (pthread_create(&ws[i].tid, NULL, worker_run, &ws[i]) != 0) {
			fprintf(stderr, "pthread_create\n");
			break;
		}
		started++;
	}
	if (started == 0) {
		for (unsigned i = 0; i < c->threads; i++)
			free(ws[i].bufmem);
		free(ws);
		return 1;
	}

	struct timespec sleepts = { .tv_sec = c->runtime, .tv_nsec = 0 };
	nanosleep(&sleepts, NULL);
	stop = 1;

	for (unsigned i = 0; i < started; i++)
		pthread_join(ws[i].tid, NULL);
	uint64_t end_ns = now_ns();

	double elapsed_s = (double)(end_ns - start_ns) / 1e9;
	if (elapsed_s <= 0)
		elapsed_s = 1e-9;

	uint64_t total_ios = 0, total_bytes = 0, total_errors = 0;
	uint64_t *agg = calloc(HIST_BUCKETS, sizeof(uint64_t));
	if (!agg) { perror("calloc"); }
	for (unsigned i = 0; i < c->threads; i++) {
		total_ios += ws[i].ios;
		total_bytes += ws[i].bytes;
		total_errors += ws[i].errors;
		if (agg)
			for (unsigned b = 0; b < HIST_BUCKETS; b++)
				agg[b] += ws[i].hist[b];
	}

	double iops = (double)total_ios / elapsed_s;
	double mbps = ((double)total_bytes / (1024.0 * 1024.0)) / elapsed_s;
	uint64_t p50 = agg ? percentile(agg, total_ios, 0.50) : 0;
	uint64_t p99 = agg ? percentile(agg, total_ios, 0.99) : 0;
	uint64_t p999 = agg ? percentile(agg, total_ios, 0.999) : 0;

	struct buf out = {0};
	buf_lit(&out, "{\"block_bench\":{");
	buf_lit(&out, "\"dev\":");
	buf_json_str(&out, c->path);
	buf_lit(&out, ",\"rw\":");
	buf_json_str(&out, mode_name(c->mode));
	buf_printf(&out, ",\"qd\":%u,\"bs\":%u", c->threads, c->bs);
	buf_printf(&out, ",\"span_bytes\":%llu", (unsigned long long)span);
	buf_printf(&out, ",\"runtime_cfg_s\":%u", c->runtime);
	buf_printf(&out, ",\"elapsed_s\":%.6f", elapsed_s);
	buf_printf(&out, ",\"ios_completed\":%llu", (unsigned long long)total_ios);
	buf_printf(&out, ",\"ios_ok\":%llu", (unsigned long long)total_ios);
	buf_printf(&out, ",\"errors\":%llu", (unsigned long long)total_errors);
	buf_printf(&out, ",\"bytes\":%llu", (unsigned long long)total_bytes);
	buf_printf(&out, ",\"iops\":%.1f", iops);
	buf_printf(&out, ",\"mb_per_s\":%.2f", mbps);
	buf_printf(&out, ",\"lat_us_p50\":%llu", (unsigned long long)p50);
	buf_printf(&out, ",\"lat_us_p99\":%llu", (unsigned long long)p99);
	buf_printf(&out, ",\"lat_us_p999\":%llu", (unsigned long long)p999);
	const char *status = (total_ios > 0 && total_errors == 0) ? "ok"
			   : (total_ios > 0 ? "degraded" : "fail");
	buf_lit(&out, ",\"status\":");
	buf_json_str(&out, status);
	buf_lit(&out, "}}");
	printf("%s\n", out.p);
	fflush(stdout);
	free(out.p);
	free(agg);

	for (unsigned i = 0; i < c->threads; i++)
		free(ws[i].bufmem);
	free(ws);

	return status[0] == 'f' ? 1 : 0;
}

int main(int argc, char **argv)
{
	struct cfg c = {
		.path = getenv("BENCH_DEV") ? getenv("BENCH_DEV") : "/dev/vblk1",
		.mode = RW_RANDREAD,
		.threads = 32,
		.bs = 4096,
		.span = 512ULL * 1024 * 1024,
		.runtime = 12,
	};
	int do_smoke = 0;
	int do_sweep = 0;

	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--dev") && i + 1 < argc)
			c.path = argv[++i];
		else if (!strcmp(argv[i], "--sweep"))
			do_sweep = 1;
		else if (!strcmp(argv[i], "--rw") && i + 1 < argc) {
			const char *m = argv[++i];
			if (!strcmp(m, "seqread")) c.mode = RW_SEQREAD;
			else if (!strcmp(m, "randread")) c.mode = RW_RANDREAD;
			else if (!strcmp(m, "seqwrite")) c.mode = RW_SEQWRITE;
			else if (!strcmp(m, "randwrite")) c.mode = RW_RANDWRITE;
			else { fprintf(stderr, "bad --rw %s\n", m); return 2; }
		} else if (!strcmp(argv[i], "--threads") && i + 1 < argc)
			c.threads = (unsigned)strtoul(argv[++i], NULL, 0);
		else if (!strcmp(argv[i], "--qd") && i + 1 < argc)
			c.threads = (unsigned)strtoul(argv[++i], NULL, 0);
		else if (!strcmp(argv[i], "--bs") && i + 1 < argc)
			c.bs = (unsigned)strtoul(argv[++i], NULL, 0);
		else if (!strcmp(argv[i], "--span") && i + 1 < argc)
			c.span = strtoull(argv[++i], NULL, 0);
		else if (!strcmp(argv[i], "--runtime") && i + 1 < argc)
			c.runtime = (unsigned)strtoul(argv[++i], NULL, 0);
		else if (!strcmp(argv[i], "--smoke"))
			do_smoke = 1;
		else {
			fprintf(stderr, "unknown arg: %s\n", argv[i]);
			return 2;
		}
	}

	if (c.threads == 0 || c.threads > 1024) {
		fprintf(stderr, "threads out of range\n");
		return 2;
	}
	if (c.bs == 0 || (c.bs % 512) != 0) {
		fprintf(stderr, "bs must be a nonzero multiple of 512\n");
		return 2;
	}
	if (c.runtime == 0) {
		fprintf(stderr, "runtime must be > 0\n");
		return 2;
	}

	if (do_smoke) {
		int rc = unaligned_smoke(c.path);
		printf("{\"block_bench_smoke\":{\"dev\":");
		struct buf sb = {0};
		buf_json_str(&sb, c.path);
		printf("%s,\"unaligned_100b_read\":%s}}\n", sb.p,
		       rc == 0 ? "\"ok\"" : "\"fail\"");
		free(sb.p);
		return rc == 0 ? 0 : 1;
	}

	int oflags = (is_write(c.mode) || do_sweep) ? O_RDWR : O_RDONLY;
	int tfd = open(c.path, oflags);
	if (tfd < 0) {
		fprintf(stderr, "open(%s): %s\n", c.path, strerror(errno));
		return 1;
	}

	/* Determine device size; clamp span to it. */
	uint64_t dev_bytes = 0;
	struct stat st;
	if (fstat(tfd, &st) == 0) {
		if (S_ISBLK(st.st_mode)) {
#ifdef BLKGETSIZE64
			if (ioctl(tfd, BLKGETSIZE64, &dev_bytes) != 0)
				dev_bytes = 0;
#endif
			if (dev_bytes == 0 && st.st_size > 0)
				dev_bytes = (uint64_t)st.st_size;
		} else {
			dev_bytes = (uint64_t)st.st_size;
		}
	}

	int rc = 0;
	if (do_sweep) {
		/*
		 * One boot, whole matrix: the pre/post-fix delta shows up as
		 * QD scaling, so sweep queue depth per mode against the single
		 * open fd. Reads first (non-destructive), then writes.
		 */
		static const unsigned qds[] = { 1, 2, 4, 8, 16, 32, 64 };
		static const enum rw_mode modes[] = {
			RW_RANDREAD, RW_SEQREAD, RW_RANDWRITE, RW_SEQWRITE,
		};
		for (unsigned mi = 0; mi < sizeof(modes) / sizeof(modes[0]); mi++) {
			c.mode = modes[mi];
			for (unsigned qi = 0; qi < sizeof(qds) / sizeof(qds[0]); qi++) {
				c.threads = qds[qi];
				rc |= run_workload(tfd, &c, dev_bytes);
			}
		}
	} else {
		rc = run_workload(tfd, &c, dev_bytes);
	}

	close(tfd);
	return rc;
}
